// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/chuckha/cluster-api/errors

package errors

// A more descriptive kind of error that represents an error condition that
// should be set in the Machine.Status. The "Reason" field is meant for short,
// enum-style constants meant to be interpreted by machines. The "Message"
// field is meant to be read by humans.
MachineError: {
	Reason:  MachineStatusError
	Message: string
}
