// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/chuckha/cluster-api/api/core/v1alpha2

// +k8s:conversion-gen=github.com/chuckha/cluster-api/pkg/apis/deprecated/v1alpha1
package v1alpha2
