// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/chuckha/cluster-api/api/core/v1alpha2

// Package v1alpha2 contains API Schema definitions for the cluster v1alpha2 API group
// +kubebuilder:object:generate=true
// +groupName=cluster.x-k8s.io
package v1alpha2
